config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'my-account', to: 'users#show', as: 'user'
  get 'user/:id', to: 'users#profile', as: 'user_profile'
  get 'community', to: 'pages#community'
  get 'about-us', to: 'pages#about_us'
  get 'chats', to: 'chatrooms#index', as: 'chats'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do
       member do
         post 'toggle_favorite', to: "products#toggle_favorite"
     end
    resources :chatrooms, only: [:new, :create]
    resources :bookings, only: [:create, :new] do
      resources :deliveries, only: [:new, :create]
      collection do
        get :confirmation
      end
    end
    resources :product_reviews, only: [:create]
  end
  resources :bookings, only: [:update, :destroy]
  resources :user_reviews, only: [:create]
  resources :orders, only: [:show, :create]


  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # to access the chatrooms from outside the products routes
  # we can unnest the chatrooms show and the messages create from the products
  # and just put it outside the loop
  resources :chatrooms, only: [:show, :destroy] do
    resources :messages, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :bookings
  has_many :requested_bookings, through: :products, source: :bookings
  has_many :user_reviews
  has_many :chatrooms
  has_one_attached :photo
  has_many :orders
  # validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  # validates :first_name, presence: true
  # validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_favoritor
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @pending_bookings = Booking.where(status: "Pending", user: current_user)
  end

  def profile
    @user = User.find(params[:id])
  end

end

app/views/users/profile.html.erb
<div class="container d-flex mt-5 align-items-center">
  <% if @user.photo.attached? %>
        <%= cl_image_tag @user.photo.key, height: 300, width: 400, crop: :fill, class: 'avatar-large m-3' %>
  <% else %>
        <img class="avatar-large m-3" src="https://source.unsplash.com/1DjbGRDh7-E/1600x900" />
  <% end %>
  <div class="profile-details">
    <h1>Hi, I'm <%= @user.first_name.capitalize %></h1>
  </div>
  <%= link_to "Follow", "#", class: "btn btn-ghost-3", id: "btn-ghost-3" %>
  <div class="dropdown">
    <button class="btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-bars"></i>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="#">Report</a>
      <a class="dropdown-item" href="#">Block</a>
    </div>
  </div>
</div>

<hr>

<div class="container">
  <h1><%= @user.first_name.capitalize %>'s products</h1>
  <% if @user.products.length > 0 %>
    <div class="row">
      <% @user.products.each do |product| %>
        <div class="col-sm-6 col-md-3">
          <%= link_to product_path(product) do %>
            <div class="card-product rounded mt-3">
              <%# add cloudinary 1st image %>
              <div class="img-wrapper">
                <%= cl_image_tag product.photos[0].key, height: 300, width: 200, crop: :fill %>
                <%# <img src="https://source.unsplash.com/VlMMBxSZuSI/200x300" /> %>
              </div>
              <div class="card-product-infos">
            <div>
              <h2 class=""><%= product.name.upcase %></h2>
              <p><%= product.category.upcase %></p>
            </div>
            <h2 class="card-product-pricing"><%= humanized_money_with_symbol(product.price) %></h2>
            <i class="far fa-heart card-product-save"></i>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    <% else %>
    <h4 class="m-5 text-center">Unfortunately <%= @user.first_name %> has no products for rental.</h4>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container d-flex mt-5 align-items-start">
  <% if current_user.photo.attached? %>
  <%= cl_image_tag current_user.photo.key, height: 400, width: 400, crop: :fill, class: 'avatar-large avatar-profile m-3' %>
  <% else %>
  <img class="avatar-large avatar-profile" src="https://source.unsplash.com/1DjbGRDh7-E/1600x900" />
  <% end %>
  <div class="my-account-details ml-4">
    <h1 class="mb-5 mt-3">Hi, <%= current_user.first_name.capitalize %></h1>
    <hr>
    <br>
    <p><i class="fas fa-user"></i> <%= current_user.username %></p>
    <h6>Check out your products and bookings below.</h6>
  </div>
  <hr>
</div>

<div class="container mt-3">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Wardrobe</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Pending Bookings</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="requested-tab" data-toggle="tab" href="#requested" role="tab" aria-controls="requested" aria-selected="false">Requested Bookings</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <div class="container mt-3">
        <div class="my-account-products">
          <h1>My Wardrobe</h1>
          <% if current_user.products.count> 0 %>
          <%= link_to 'Add a new product' , new_product_path, class: "btn btn-flat" %>
          <% end %>
        </div>
        <div class="row">
          <% if current_user.products.length> 0 %>
          <% current_user.products.each do |product| %>
          <div class="col-sm-6 col-md-3">
            <%= link_to product_path(product) do %>
            <div class="card-product rounded mt-3">
              <div class="img-wrapper">
                <%= cl_image_tag product.photos[0].key, height: 300, width: 200, crop: :fill %>
                <%# <img src="https://source.unsplash.com/VlMMBxSZuSI/200x300" /> %>
              </div>
              <div class="card-product-infos">
                <div>
                  <h2 class=""><%= product.name.upcase %></h2>
                  <p><%= product.category.upcase %></p>
                </div>
                <h2 class="card-product-pricing"><%= humanized_money_with_symbol(product.price) %></h2>
                <i class="far fa-heart card-product-save"></i>
              </div>
            </div>
            <% end %>
          </div>
          <% end %>
          <% else %>
          <div class="container my-account-products-container">
            <h4 class="m-5 text-center">You don't have any items to rent. Anything you want to rent out?</h4>
            <%= link_to 'Get Started' , new_product_path, class: "btn btn-flat" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
      <% @pending_user_bookings=current_user.bookings.select do |booking| %>
      <% booking.status=="Pending" %>
      <% end %>

      <div class="container mt-3">
        <% if @pending_user_bookings.length> 0 %>
        <h1>Pending bookings</h1>
        <% else %>
        <h1>You currently have no pending bookings</h1>
        <% end %>
        <div class="row">
          <% current_user.bookings.each do |booking| %>
          <% booking.product %>
          <div class="col-sm-6 col-md-3">
            <%= link_to product_path(booking.product) do %>
            <div class="card-product rounded mt-3">
              <%# add cloudinary 1st image %>
              <div class="img-wrapper">
                <%= cl_image_tag booking.product.photos[0].key, height: 300, width: 200, crop: :fill %>
                <%# <img src="https://source.unsplash.com/VlMMBxSZuSI/200x300" /> %>
              </div>
              <div class="card-product-infos">
                <div>
                  <h2 class="">
                    <%= booking.product.name.upcase %>
                  </h2>
                  <p>
                    <%= booking.product.category.upcase %>
                  </p>
                  <p>BOOKING STATUS:<%= booking.status %>
                  </p>
                  <h2 class="card-product-pricing">
                    <%= humanized_money_with_symbol(booking.product.price) %>
                  </h2>
                </div>
                <i class="far fa-heart card-product-save"></i>
              </div>
            </div>
            <% end %>
            <% if booking.status=="Pending" %>
            <% if current_user==booking.product.user %>
            <div class="accept-decline-buttons">
              <%= form_with(model: booking, url: booking_path(booking), remote: true, method: "patch"
              ) do |f| %>
              <%= f.hidden_field :status, value: "Accepted" %>
              <%= f.submit "Accept" , class: "btn btn-success" %>
              <% end %>
              <%= form_with(model: booking, url: booking_path(booking), remote: true,
              method: "patch" ) do |f| %>
              <%= f.hidden_field :status, value: "Declined" %>
              <%= f.submit "Decline" , class: "btn btn-danger" %>
              <% end %>
            </div>
            <% end %>
            <% elsif booking.orders.find_by(user: booking.user).state=="Paid" %>
            <div class="d-flex justify-content-around align-items-center">
              <p>paid</p>
              <%= link_to booking_path(booking), method: :delete, remote: true do%>
              <i class="fas fa-times"></i>
              <% end %>
            </div>
            <% elsif booking.status=="Declined" %>
            <div class="d-flex justify-content-around align-items-center">
              <p>Declined</p>
              <%= link_to booking_path(booking), method: :delete, remote: true do%>
              <i class="fas fa-times"></i>
              <% end %>
            </div>
            <% else %>
            <button id="pay-<%= booking.id%>" class="btn btn-primary pay-button">PAYNOW</button>
            <script src="https://js.stripe.com/v3/"></script>
            <script>
              document.getElementById('pay-<%= booking.id%>').addEventListener('click', () => {
                const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
                stripe.redirectToCheckout({
                  sessionId: '<%= booking.orders.find_by(user: booking.user).checkout_session_id %>'
                });
              });
            </script>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="requested" role="tabpanel" aria-labelledby="requested-tab">
      <div class="container mt-3">
        <% if current_user.requested_bookings.length> 0 %>
        <h1>Booking Requests</h1>
        <% else %>
        <h1>You currently have no booking requests</h1>
        <% end %>
        <div class="row">
          <% current_user.requested_bookings.each do |booking| %>
          <% booking.product %>
          <div class="col-sm-6 col-md-3">
            <%= link_to product_path(booking.product) do %>
            <div class="card-product rounded mt-3">
              <div class="img-wrapper">
                <%= cl_image_tag booking.product.photos[0].key, height: 300, width: 200, crop: :fill %>
                <%# <img src="https://source.unsplash.com/VlMMBxSZuSI/200x300" /> %>
              </div>
              <div class="card-product-infos">
                <div>
                  <h2 class="">
                    <%= booking.product.name.upcase %>
                  </h2>
                  <p>
                    <%= booking.product.category.upcase %>
                  </p>
                  <p>BOOKING STATUS:<%= booking.status %>
                  </p>
                </div>
                <h2 class="card-product-pricing">
                  <%= humanized_money_with_symbol(booking.product.price) %>
                </h2>
                <i class="far fa-heart card-product-save"></i>
              </div>
            </div>
            <% end %>
            <div class="d-flex justify-content-around align-items-center">
              <% if booking.status=="Pending" %>
              <% if current_user==booking.product.user %>
              <div class="accept-decline-buttons">
                <%= form_with(model: booking, url: booking_path(booking), remote: true, method: :patch) do
                |f| %>
                <%= f.hidden_field :status, value: "Accepted" %>
                <%= f.submit "Accept" , class: "btn btn-success accept-btn" %>
                <% end %>
                <%= form_with(model: booking, url: booking_path(booking), remote: true,
                method: "patch" ) do |f| %>
                <%= f.hidden_field :status, value: "Declined" %>
                <%= f.submit "Decline" , class: "btn btn-primary decline-btn" %>
                <% end %>
              </div>
              <% end %>
              <% end %>
              <% if booking.orders.length> 0 %>
              <% if booking.orders.find_by(user: booking.user).state=="Paid" ||
              booking.status=="Declined" %>
              <p>
                <%= booking.status=="Declined" ? "Declined" : "Paid" %>
              </p>
              <%= link_to booking_path(booking), method: :delete, remote: true do%>
              <i class="fas fa-times"></i>
              <% end %>
              <% end %>
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <hr>
</div>