config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'my-account', to: 'users#show', as: 'user'
  get 'user/:id', to: 'users#profile', as: 'user_profile'
  get 'community', to: 'pages#community'
  get 'about-us', to: 'pages#about_us'
  get 'chats', to: 'chatrooms#index', as: 'chats'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do
       member do
         post 'toggle_favorite', to: "products#toggle_favorite"
     end
    resources :chatrooms, only: [:new, :create]
    resources :bookings, only: [:create, :new] do
      resources :deliveries, only: [:new, :create]
      collection do
        get :confirmation
      end
    end
    resources :product_reviews, only: [:create]
  end
  resources :bookings, only: [:update, :destroy]
  resources :user_reviews, only: [:create]
  resources :orders, only: [:show, :create]


  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # to access the chatrooms from outside the products routes
  # we can unnest the chatrooms show and the messages create from the products
  # and just put it outside the loop
  resources :chatrooms, only: [:show, :destroy] do
    resources :messages, only: :create
  end
end

app/views/shared/_accordion.html.erb
<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header accordion-card" id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Our sustainability commitments
        </button>
      </h2>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
        <div class="card-body-details">
          <h3 class="accordion-details-title">For every week long rental with us, we promise to:</h3>
          <div class="accordion-card-details">
            <div><p class="d-flex align-items-center"><i class="fas fa-tree font-awesome fa-2x"></i>Plant 1 tree</p></div>
            <div><p class="d-flex align-items-center"><i class="fas fa-recycle font-awesome fa-2x"></i>Recycle an piece of old clothing</p></div>
            <div><p class="d-flex align-items-center"><i class="fas fa-dollar-sign font-awesome fa-2x"></i>Invest in our green technology partners.</p></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header accordion-card" id="headingTwo">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Listing your items is super simple
        </button>
      </h2>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">
        <strong>1. List your item for free 👗 </strong> <br><strong>2. Rent it, ship it, get it back 📦 </strong> <br><strong>3. Do it all again 🔁 </strong>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header accordion-card" id="headingThree">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Renting items is super simple
        </button>
      </h2>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
      <div class="card-body">
         <strong>1. Find it 🔍 </strong> <br><strong>2. Rent it, recieve it 📦 </strong> <br><strong>3. Help the planet and your wallet in the process 🌍</strong>
      </div>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://source.unsplash.com/HbAddptme1Q/2400x1600);">
  <div class="container banner-text slide-right fade-in-text">
    <h2>Fashion doesn't have to cost the earth.</h2>
    <p class="banner-p">Join the <strong>rental revolution</strong>.</p>
  </div>
</div>


<%# qqF5oyL9CMk %>
<%# X_gl40e7BDk %>
<%# JxSwoyKQP-s %>
<%# QN507MdnxRQ %>
<%# HbAddptme1Q %>

app/views/shared/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <% @user_products.each_slice(3).with_index do |slice, index|  %>
      <div class="carousel-item <%= 'active' if index == 0 %> ">
        <div class="cards-wrapper">
          <% slice.each do |product| %>
            <%= link_to product_path(product) do %>
              <div class="card-product carousel-card rounded mt-3">
                <%# add cloudinary 1st image %>
                <div class="img-wrapper">
                  <%= cl_image_tag product.photos[0].key, height: 300, width: 200, crop: :fill %>
                  <%# <img src="https://source.unsplash.com/VlMMBxSZuSI/200x300" /> %>
                </div>
                <div class="card-product-infos">
                  <div>
                    <h2 class=""><%= product.name.upcase %></h2>
                    <p><%= product.category.upcase %></p>
                  </div>
                  <h2 class="card-product-pricing"><%= humanized_money_with_symbol(product.price) %></h2>
                  <i class="far fa-heart card-product-save"></i>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_copy-code-here.html.erb
<div class="nav navbar navbar-center navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

app/views/shared/_filter_form.html.erb
<%= form_tag products_path, method: :get, class: 'filter-form' do %>
 <% label_name = ['dresses', 'trousers', 'tops', 'shoes', 'jumpsuits', 'sweaters', 'jeans', 'jackets', 'accessories'] %>
  <% ['dress', 'trouser', 'top', 'shoes', 'jumpsuit', 'sweater', 'jeans', 'jacket', 'accessories'].each_with_index do |category, index| %>
    <%= radio_button_tag "category", category,  false, class: 'classic-checkbox', :id => "category#{index}" %>
    <%= label_tag("category#{index}", label_name[index].upcase) %>
  <% end %>
  <br>
  <h4 class="mt-2">Size: UK</h4>
  <hr>
  <% ['6', '8', '10', '12', '14', '16'].each_with_index do |size, index| %>
    <%= radio_button_tag "size", size,  false, class: 'classic-checkbox size-filter', :id => "size#{index}" %>
    <%= label_tag("size#{index}", size.upcase) %>
  <% end %>
    <br>
    <br>
    <%= submit_tag "Filter Products", class: "btn btn-primary btn-block" %>
    <%= link_to 'Reset Filters', products_path, class: 'btn btn-light btn-block' %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="row footer-details justify-content-center">
    <div class="col-md-10">
      <div>
        <div class="row footer-details-row">
          <div class="col-sm-4 col-md-2">
            <h2>Company</h2>
            <%= link_to "ABOUT US", about_us_path, class: "footer-details-link"%>
            <%= link_to "COMMUNITY", community_path, class: "footer-details-link" %>
            <a href="#" class="footer-details-link">CHARITY</a>
            <a href="#" class="footer-details-link">PRESS</a>
            <a href="#" class="footer-details-link">CAREERS</a>
            <a href="#" class="footer-details-link">OUR PARTNERS</a>
            <a href="#" class="footer-details-link">CONTACT US</a>
          </div>
          <div class="col-sm-4 col-md-2">
            <h2>Legal</h2>
            <a href="#" class="footer-details-link">TERMS OF SERVICE</a>
            <a href="#" class="footer-details-link">PRIVACY POLICY</a>
            <a href="#" class="footer-details-link">COOKIES POLICY</a>
          </div>
          <div class="col-sm-4 col-md-2">
            <h2>Explore</h2>
            <a href="#" class="footer-details-link">FAQS</a>
            <a href="#" class="footer-details-link">DELIVERY</a>
            <a href="#" class="footer-details-link">GIFT CARDS</a>
            <a href="#" class="footer-details-link">RENTING WITH US</a>
            <a href="#" class="footer-details-link">DRY CLEANING</a>
          </div>
        </div>
      </div>
    </div>
  </div>
   <div class="row d-flex justify-content-space-between pb-3">
    <div class="col-md-10 footer-links">
      <a href="#" href="#"><i class="fab fa-github"></i></a>
      <a href="#" href="#"><i class="fab fa-instagram"></i></a>
      <a href="#" href="#"><i class="fab fa-facebook"></i></a>
      <a href="#" href="#"><i class="fab fa-twitter"></i></a>
      <a href="#" href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      Mannequinn 2021 <i class="far fa-copyright"></i>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="container-fluid header-title">
  <div class="row">
    <div class="col-lg-4 pt-3"><p class="currency px-2 font-weight-bold">GBP £</p></div>
    <div class="text-center col-lg-4 pb-1 pt-4">
       <%= link_to root_path, class: "brand-title" do %>
         <h1 class="brand-title">MANNEQUINN</h1>
       <% end %>
    </div>
    <div class="user-corner col-lg-4 pt-3 d-flex justify-content-end align-items-start"">
      <% if user_signed_in? %>
        <p class="fs-1 px-2"><i class="fas fa-user"></i> <%= current_user.username.downcase %></p>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, remote: false, class: 'fs-1 px-2' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<%# desktop nav ***************************** %>

<nav data-controller="navbar" id="navbar" class="p-2 navbar-mqn desktop-nav-section">
  <ul class="nav justify-content-center">
    <li class="nav-item">
      <h1 id="brand" class="brand-title-nav d-none">MANNEQUINN</h1>
    </li>
    <li class="nav-item">
      <%= link_to 'Home', root_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Rent Clothing', products_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%# <a class="nav-link" href="#">Community</a> %>
       <%= link_to 'Community', community_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%# <a class="nav-link" href="#">About Us</a> %>
      <%= link_to 'About Us', about_us_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%# <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Sign in/Register</a> %>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="left: -70px">
            <a class="dropdown-item" href="#"></a>
            <%= link_to 'Profile', user_path, class: 'dropdown-item' %>
            <%= link_to 'Messages', chats_path, class: 'dropdown-item' %>
            <%= link_to 'Add a Listing', new_product_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, remote: false, class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <%= link_to 'Sign in/Register', new_user_session_path, class: 'nav-link' %>
      <% end %>
    </li>
    <li>
      <div class="input-group rounded search-bar">
        <%= form_tag products_path, method: :get do %>
        <div class="d-flex">
            <%= text_field_tag :query,
                              params[:query],
                              class: "form-control",
                              id: "search-addon",
                              placeholder: "Start renting!"
            %>
            <%= button_tag(type: "submit", class: "input-group-text border-0") do %>
              <span class="" id="search-addon">
                <i class="fas fa-search"></i>
              </span>
            <% end %>
          </div>
        <% end %>
      </div>
    </li>
  </ul>
</nav>

<%# mobile nav ***************************** %>

<nav class="mobile-nav-section navbar-mqn navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
          <%= link_to 'Rent Clothing', products_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Community</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About Us</a>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, remote:false, class: 'nav-link' %>
        <% else %>
          <%= link_to 'Sign in/Register', new_user_session_path, class: 'nav-link' %>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="input-group rounded search-bar">
    <%= form_tag products_path, method: :get do %>
    <div class="d-flex">
        <%= text_field_tag :query,
                          params[:query],
                          class: "form-control",
                          id: "search-addon",
                          placeholder: "Start renting!"
        %>
        <%= button_tag(type: "submit", class: "input-group-text border-0") do %>
          <span class="" id="search-addon">
            <i class="fas fa-search"></i>
          </span>
        <% end %>
      </div>
    <% end %>
  </div>
</nav>

app/views/shared/_new_booking.html.erb
<%= simple_form_for([@product, @booking]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
      <%= f.input :start_date, as: :date, html5: true %>
      <%= f.input :end_date, as: :date, html5: true %>
  </div>
  <div class="form-actions">
    <%= f.submit 'REQUEST BOOKING', class: 'btn btn-primary btn-book' %>
  </div>
<% end %>

app/views/shared/_new_form.html.erb
<%= simple_form_for [@user, @product] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :category, collection: Product::CATEGORYS, include_blank: false%>
    <%= f.input :description %>
    <%= f.input :size, collection: Product::SIZES, include_blank: false %>
    <%= f.input :price %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.submit 'ADD ITEM', class: 'btn btn-primary btn-book' %>
  </div>
<% end %>

app/views/shared/_sort-by.html.erb
<%= form_tag products_path, method: :get, class: 'sort-by' do %>
  <%= select_tag "sort-by", "<option value='accending'>Price: Low to High</option><option value='decending'>Price: High to Low</option>".html_safe, class: 'form_input sort-dropdown' %>
  <%= submit_tag "Sort", class: "btn btn-primary sort-submit" %>
<% end %>