config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'my-account', to: 'users#show', as: 'user'
  get 'user/:id', to: 'users#profile', as: 'user_profile'
  get 'community', to: 'pages#community'
  get 'about-us', to: 'pages#about_us'
  get 'chats', to: 'chatrooms#index', as: 'chats'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do
       member do
         post 'toggle_favorite', to: "products#toggle_favorite"
     end
    resources :chatrooms, only: [:new, :create]
    resources :bookings, only: [:create, :new] do
      resources :deliveries, only: [:new, :create]
      collection do
        get :confirmation
      end
    end
    resources :product_reviews, only: [:create]
  end
  resources :bookings, only: [:update, :destroy]
  resources :user_reviews, only: [:create]
  resources :orders, only: [:show, :create]


  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # to access the chatrooms from outside the products routes
  # we can unnest the chatrooms show and the messages create from the products
  # and just put it outside the loop
  resources :chatrooms, only: [:show, :destroy] do
    resources :messages, only: :create
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :product_reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :chatrooms, dependent: :destroy
  has_many_attached :photos

  validates :name, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :size, :price, presence: true

  SIZES = ['6', '8', '10', '12', '14', '16', '18', '20']
  CATEGORYS = ['dress', 'trouser', 'top', 'shoes', 'jumpsuit', 'sweater', 'jeans', 'jacket', 'accessories']
  COLOR = ['red', 'pink', 'white', 'blue', 'green', 'black', 'multicolor']
  # CATEGORY = ['Tops', 'Bottoms', 'Underwear', 'Outerwear', 'Shoes']

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description_and_size_and_category,
    against: [ :name, :description, :size, :category ],
    associated_against: { user: [ :username, :first_name, :last_name ] },
    using: {
      tsearch: { prefix: true }
    }

  monetize :price_cents

  acts_as_favoritable
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: :toggle_favorite

  def index
    if params[:query].present?
      filter_query_results(params[:query])
    elsif params[:category].present? || params[:size].present?
      filter_category_results(params)
    elsif params["sort-by"].present?
      filter_sort_results(params["sort-by"])
    else
      @products = Product.all
      delete_sessions
    end
  end


  def show
    @products = Product.all
    @product_review = ProductReview.new(product: @product)
    @user_products = @product.user.products.where.not(id: @product.id)
    # @chatroom = Chatroom.find_by(user: current_user, product: @product)
    @chatroom = Chatroom.new
  end

  def new
    @product = Product.new
    # we need to authorize anyone to make a product (when they have an account)
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated'
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

   def toggle_favorite
    @product = Product.find_by(id: params[:id])
    current_user.favorited?(@product)  ?current_user.unfavorite(@product) : current_user.favorite(@product)
    redirect_to product_path(@product)
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :category, :size, :price, photos:[])
  end

  def filter_query_results(params)
    session[:search_query] = params
    if session[:search_category] && session[:search_sort]
      search = Product.where("category ILIKE ?", "%#{session[:search_category]}%")
      array = search.search_by_name_and_description_and_size_and_category(params)
      @products = sort(array, session[:search_sort])
    elsif session[:search_category]
      search = Product.where("category ILIKE ?", "%#{session[:search_category]}%")
      @products = search.search_by_name_and_description_and_size_and_category(params)
    elsif session[:search_sort]
      array = Product.search_by_name_and_description_and_size_and_category(params)
      @products = sort(array, session[:search_sort])
    else
      @products = Product.search_by_name_and_description_and_size_and_category(params)
    end
  end

  def filter_category_results(params)
    session[:search_category] = params
    if session[:search_query] && session[:search_sort]
      search = Product.search_by_name_and_description_and_size_and_category(session[:search_query])
      size_array = search.where("size ILIKE ?", "%#{params[:size]}%")
      array = size_array.where("category ILIKE ?", "%#{params[:category]}%")
      @products = sort(array, session[:search_sort])
    elsif session[:search_query]
      search = Product.search_by_name_and_description_and_size_and_category(session[:search_query])
      size_array = search.where("size ILIKE ?", "%#{params[:size]}%")
      @products = size_array.where("category ILIKE ?", "%#{params[:category]}%")
    elsif session[:search_sort]
      size_array = Product.where("size ILIKE ?", "%#{params[:size]}%")
      array = size_array.where("category ILIKE ?", "%#{params[:category]}%")
      @products = sort(array, session[:search_sort])
    else
      size_array = Product.where("size ILIKE ?", "%#{params[:size]}%")
      @products = size_array.where("category ILIKE ?", "%#{params[:category]}%")
    end
  end

  def filter_sort_results(params)
    session[:search_sort] = params
    if session[:search_query] && session[:search_category]
      search = Product.search_by_name_and_description_and_size_and_category(session[:search_query])
      array = search.where("category ILIKE ?", "%#{session[:search_category]}%")
      @products = sort(array, params)
    elsif session[:search_query]
      array = Product.search_by_name_and_description_and_size_and_category(session[:search_query])
      @products = sort(array, params)
    elsif session[:search_category]
      array = search.where("category ILIKE ?", "%#{session[:search_category]}%")
      @products = sort(array, params)
    else
      @products = sort(Product.all, params)
    end
  end

  def sort(array, sort_by)
    if sort_by == "accending"
      array.sort_by(&:price_cents)
    else
      array.sort_by(&:price_cents).reverse
    end
  end

  def delete_sessions
    session.delete("search_query")
    session.delete("search_sort")
    session.delete("search_category")
  end
end

app/views/products/edit.html.erb
<div class="container">
  <h1>Edit your product</h1>
  <%= render 'shared/new_form' %>
</div>

app/views/products/index.html.erb
<%# <div class="container text-center mt-3 index-title">
      <h1>All Clothing</h1>
</div> %>

<div class="container-fluid px-5 text-right mt-3">
   <%= render 'shared/sort-by' %>
</div>

<div class="container-fluid container-fluid-index py-1">
  <div class="row">
    <div class="col-lg-3">
      <div class="filter-bar px-4 py-5 mt-3">
        <h4>Category</h4>
        <hr>
        <%= render 'shared/filter_form' %>
      </div>
    </div>
    <div class="col-lg-9">
      <div class="row">
        <% if @products.length.zero?  %>
          <div class="col-lg-12">
            <h5>Sorry there are no results that match your search criteria. Please try again</h5>
          </div>
        <% else %>
          <% @products.each do |product| %>
            <div class="col-lg-4 grow col-md-6">
              <%= link_to product_path(product) do %>
                <div class="card-product rounded mt-3" data-aos="zoom-out">
                  <div class="img-wrapper">
                    <% if product.photos.attached? %>
                      <%= cl_image_tag product.photos[0].key, height: 300, width: 200, crop: :fill %>
                    <% else %>
                      <img src="https://source.unsplash.com/VlMMBxSZuSI/200x300" />
                    <% end %>
                  </div>
                  <% product.bookings.each do |booking| %>
                    <% if (booking.start_date .. booking.end_date).cover?(Date.today) %>
                      <p id="currently-rented">CURRENTLY RENTED</p>
                    <% end %>
                  <% end %>
                  <div class="card-product-infos">
                    <div>
                      <p><%= product.category.upcase %></p>
                    </div>
                    <h6 class="card-product-pricing"><%= humanized_money_with_symbol(product.price) %></h6>
                    <i class="far fa-heart card-product-save"></i>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container new-product-container col-lg-6" >
<h1>ADD A NEW PRODUCT</h1>
<%= render 'shared/new_form' %>
</div>

app/views/products/show.html.erb
<div class="container all-container">
  <div class="product-actions">
    <% if current_user == @product.user  %>
      <%= link_to 'EDIT', edit_product_path(@product) %> |
      <%= link_to 'DELETE', product_path(@product), method: :delete, data:{confirm: "Are you sure you want to delete this product?"}%>
    <% end %>
  </div>
  <div class="container product-container">
    <div class="row">
      <div class="col-sm-12 col-md-8 product-image-container">
        <div id="carouselExampleIndicators-1" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <% @product.photos.each_with_index do |photo, index| %>
              <% if index == 0 %>
                <li data-target="#carouselExampleIndicators-1" data-slide-to="0" class="active"></li>
              <% else %>
                <li data-target="#carouselExampleIndicators-1" data-slide-to="<%= index %>"></li>
              <% end %>
            <% end %>
          </ol>
          <div class="carousel-inner" style=" width:100%; object-fit:cover;">
            <% if @product.photos.attached? %>
              <% @product.photos.each_with_index do |photo, index| %>
                <% if index == 0 %>
                  <div class="carousel-item active carousel-img">
                    <%= cl_image_tag photo.key, :height=>720, :crop=>"scale", style: 'width: 100%;', class: "product-img"%>
                  </div>
                <% else %>
                  <div class="carousel-item carousel-img">
                    <%= cl_image_tag photo.key, :height=>720, :crop=>"scale", style: 'width: 100%;', class: "product-img" %>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators-1" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators-1" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <div class="col-sm-12 col-md-4 details-container">
        <div class="product-details-container">
          <h2> <%= humanized_money_with_symbol(@product.price) %></h2>
          <div class="product-details">
            <% if @product.user.photo.attached? %>
              <%= cl_image_tag @product.user.photo.key, height: 200, width: 200, crop: :fill, class: 'card-trip-user avatar-bordered' %>
            <% else %>
              <img src="https://source.unsplash.com/NE0XGVKTmcA/200x200" class="card-trip-user avatar-bordered" />
            <% end %>
            <% if @product.user == current_user %>
              <p><%= link_to @product.user.username, user_path %></p>
            <% else %>
              <p><%= link_to @product.user.username, user_profile_path(@product.user) %></p>
            <% end %>
          </div>
          <hr class="horizontal-rule">
          <p><%= @product.description %></p>
          <hr class="horizontal-rule">
          <p>CATEGORY: <%= @product.category.upcase %></p>
          <p>SIZE: <%= @product.size %></p>
          <p>PRICE: <%= humanized_money_with_symbol(@product.price) %></p>
          <div class="btn-container">
          <% if @product.user != current_user %>
            <%= link_to "Ask the seller", new_product_chatroom_path(@product), class: "btn btn-ghost", id: "btn-ghost" %>
          <% end %>
          <% if user_signed_in? %>
            <% if current_user.favorited?(@product) %>
              <%= link_to "<i class='fas fa-heart'></i> Added to favourites".html_safe, toggle_favorite_product_path(@product), remote: true, method: :post, class: "btn btn-ghost", id: "btn-ghost" %>
            <% else %>
              <%= link_to "<i class='far fa-heart'></i> Add to favourites".html_safe, toggle_favorite_product_path(@product), remote: true, method: :post, class: "btn btn-ghost", id: "btn-ghost" %>
            <% end %>
          <% end %>

            <% if user_signed_in? %>
              <% if @product.user != current_user %>
                <%= link_to 'BOOK NOW', new_product_booking_path(@product), class: "btn btn-primary btn-book" %>
              <% end %>
            <% else %>
              <h6 class="text-center my-3 font-weight-bold">Please Login or Register now to book this item.</h6>
              <%= link_to "LOGIN", new_user_session_path, class: "btn btn-primary btn-book"%>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container accordion-container">
  <div class="row">
    <div class="col-sm-12 col-md-12 accordion-box">
      <%= render 'shared/accordion' %>
    </div>
  </div>
</div>

<div class="more-from-this-user mt-5">
  <h2>More from this user</h2>
</div>

<div class="other-products">
  <div class="row carousel-row">
    <div class="col-sm-12 col-md-10">
      <% if @product.user.products.length < 2 %>
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-sm-12 col-md-6">
              <p>This user has no additional products to show</p>
            </div>
          </div>
        </div>
      <% else %>
        <%= render 'shared/carousel' %>
      <% end %>
    </div>
  </div>
</div>

<div class="container reviews-container mt-5">
  <div class="row reviews-container-row">
    <div class="col-sm-12 col-md-6">
      <h2 class="add-review-text">Add a new product review</h2>
      <%= simple_form_for [@product, @product_review] do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <% if @product_review.errors.any? %>
      <div class="errors-container">
        <ul class="list-unstyled">
          <% @product_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <%= f.input :content, required: true %>
      <%= f.input :rating, collection: 1..5, required: true %>
      <%= f.button :submit, class:"btn btn-primary" %>
      <% end %>
    </div>

    <div class="col-sm-12 col-md-6">
      <h2 class="see-reviews-text">See this product's latest reviews</h2>
      <br>
      <% if @product.product_reviews.empty? %>
        <small><em>Be the first one to review this product!</em></small>
      <% else %>
      <% @product.product_reviews.last(5).each do |review| %>
      <div class="review-content">
        <p><%= review.user.email %></p>
        <p><% review.rating.times do %>
        <i class="fas fa-star star-yellow"></i>
        <% end %></p>
        <p class="mb-0"><%= review.content %></p>
        <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>